# Dev profile
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/farmers_market
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.hibernate-orm.log.sql=true
quarkus.log.level=DEBUG
quarkus.log.category."in.farmersmarket".level=DEBUG

quarkus.swagger-ui.always-include=true
